"""First migrate

Revision ID: 13682f400129
Revises: 
Create Date: 2023-07-13 14:40:27.082002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13682f400129'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('check_export_portofolios',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('perkuliahan_id', sa.BigInteger(), nullable=True),
    sa.Column('template_name', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=120), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('modified_by', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['perkuliahan_id'], ['perkuliahans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_check_export_portofolios_id'), 'check_export_portofolios', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_check_export_portofolios_id'), table_name='check_export_portofolios')
    op.drop_table('check_export_portofolios')
    # ### end Alembic commands ###
