"""update models assessment prodi

Revision ID: 226fa76592fe
Revises: 8ac49ad61e8a
Create Date: 2023-07-26 14:38:58.350368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '226fa76592fe'
down_revision = '8ac49ad61e8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
