"""First migrate

Revision ID: 7a21a94028f7
Revises: 
Create Date: 2023-06-15 22:38:23.023907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a21a94028f7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fakultas',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('nama_fakultas', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=120), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('modified_by', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fakultas_id'), 'fakultas', ['id'], unique=False)
    op.create_table('konsentrasis',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('konsentrasi', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=120), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('modified_by', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_konsentrasis_id'), 'konsentrasis', ['id'], unique=False)
    op.create_table('kurikulums',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('deskripsi', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=120), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('modified_by', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kurikulums_id'), 'kurikulums', ['id'], unique=False)
    op.create_table('module_groups',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('module_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=120), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('modified_by', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_module_groups_id'), 'module_groups', ['id'], unique=False)
    op.create_table('role_masters',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('role_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=120), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('modified_by', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_role_masters_id'), 'role_masters', ['id'], unique=False)
    op.create_table('status_mahasiswas',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('status', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=120), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('modified_by', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_status_mahasiswas_id'), 'status_mahasiswas', ['id'], unique=False)
    op.create_table('modules',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('module_group_id', sa.BigInteger(), nullable=True),
    sa.Column('module_name', sa.String(length=255), nullable=True),
    sa.Column('route', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=120), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('modified_by', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['module_group_id'], ['module_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_modules_id'), 'modules', ['id'], unique=False)
    op.create_table('prodis',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('fakultas_id', sa.BigInteger(), nullable=True),
    sa.Column('prodi', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=120), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('modified_by', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['fakultas_id'], ['fakultas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prodis_id'), 'prodis', ['id'], unique=False)
    op.create_table('child_modules',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('module_id', sa.BigInteger(), nullable=True),
    sa.Column('module_name', sa.String(length=200), nullable=True),
    sa.Column('route', sa.String(length=150), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=120), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('modified_by', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_child_modules_id'), 'child_modules', ['id'], unique=False)
    op.create_table('cpls',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('prodi_id', sa.BigInteger(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('statement', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=120), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('modified_by', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['prodi_id'], ['prodis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cpls_id'), 'cpls', ['id'], unique=False)
    op.create_table('konsentrasi_prodis',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('konsentrasi_id', sa.BigInteger(), nullable=True),
    sa.Column('prodi_id', sa.BigInteger(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=120), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('modified_by', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['konsentrasi_id'], ['konsentrasis.id'], ),
    sa.ForeignKeyConstraint(['prodi_id'], ['prodis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_konsentrasi_prodis_id'), 'konsentrasi_prodis', ['id'], unique=False)
    op.create_table('mahasiswas',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('prodi_id', sa.BigInteger(), nullable=True),
    sa.Column('status_mhs_id', sa.BigInteger(), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('nim', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=120), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('modified_by', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['prodi_id'], ['prodis.id'], ),
    sa.ForeignKeyConstraint(['status_mhs_id'], ['status_mahasiswas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mahasiswas_id'), 'mahasiswas', ['id'], unique=False)
    op.create_table('mata_kuliahs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('kurikulum_id', sa.BigInteger(), nullable=True),
    sa.Column('prodi_id', sa.BigInteger(), nullable=True),
    sa.Column('kode_mk', sa.String(length=100), nullable=True),
    sa.Column('mata_kuliah', sa.String(length=200), nullable=True),
    sa.Column('sks', sa.String(length=200), nullable=True),
    sa.Column('is_konsen', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=120), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('modified_by', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['kurikulum_id'], ['kurikulums.id'], ),
    sa.ForeignKeyConstraint(['prodi_id'], ['prodis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mata_kuliahs_id'), 'mata_kuliahs', ['id'], unique=False)
    op.create_table('role_permissions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('role_id', sa.BigInteger(), nullable=True),
    sa.Column('module_id', sa.BigInteger(), nullable=True),
    sa.Column('view', sa.Boolean(), nullable=True),
    sa.Column('write', sa.Boolean(), nullable=True),
    sa.Column('delete', sa.Boolean(), nullable=True),
    sa.Column('print', sa.Boolean(), nullable=True),
    sa.Column('export', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=120), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('modified_by', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['role_masters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_role_permissions_id'), 'role_permissions', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('prodi_id', sa.BigInteger(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('nip', sa.String(length=100), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('email_verified_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=120), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('modified_by', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['prodi_id'], ['prodis.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('nip')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('mahasiswa_doswals',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('mahasiswa_id', sa.BigInteger(), nullable=True),
    sa.Column('dosen_id', sa.BigInteger(), nullable=True),
    sa.Column('angkatan', sa.String(length=150), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=120), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('modified_by', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['dosen_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['mahasiswa_id'], ['mahasiswas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mahasiswa_doswals_id'), 'mahasiswa_doswals', ['id'], unique=False)
    op.create_table('matkul_konsentrasis',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('matkul_id', sa.BigInteger(), nullable=True),
    sa.Column('konsentrasi_id', sa.BigInteger(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=120), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('modified_by', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['konsentrasi_id'], ['konsentrasis.id'], ),
    sa.ForeignKeyConstraint(['matkul_id'], ['mata_kuliahs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matkul_konsentrasis_id'), 'matkul_konsentrasis', ['id'], unique=False)
    op.create_table('mhs_konsentrasis',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('mahasiswa_id', sa.BigInteger(), nullable=True),
    sa.Column('konsentrasi_id', sa.BigInteger(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=120), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('modified_by', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['konsentrasi_id'], ['konsentrasis.id'], ),
    sa.ForeignKeyConstraint(['mahasiswa_id'], ['mahasiswas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mhs_konsentrasis_id'), 'mhs_konsentrasis', ['id'], unique=False)
    op.create_table('perkuliahans',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('dosen_id', sa.BigInteger(), nullable=True),
    sa.Column('dosen2_id', sa.BigInteger(), nullable=True),
    sa.Column('dosen3_id', sa.BigInteger(), nullable=True),
    sa.Column('pj_dosen_id', sa.BigInteger(), nullable=True),
    sa.Column('mata_kuliah_id', sa.BigInteger(), nullable=True),
    sa.Column('prodi_id', sa.BigInteger(), nullable=True),
    sa.Column('kelas', sa.String(length=100), nullable=True),
    sa.Column('tahun_ajaran', sa.String(length=200), nullable=True),
    sa.Column('semester', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=120), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('modified_by', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['dosen2_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['dosen3_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['dosen_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['mata_kuliah_id'], ['mata_kuliahs.id'], ),
    sa.ForeignKeyConstraint(['pj_dosen_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['prodi_id'], ['prodis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_perkuliahans_id'), 'perkuliahans', ['id'], unique=False)
    op.create_table('prodi_strukturals',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('prodi_id', sa.BigInteger(), nullable=True),
    sa.Column('gpm_id', sa.BigInteger(), nullable=True),
    sa.Column('kaprodi_id', sa.BigInteger(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=120), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('modified_by', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['gpm_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['kaprodi_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['prodi_id'], ['prodis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prodi_strukturals_id'), 'prodi_strukturals', ['id'], unique=False)
    op.create_table('user_roles',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('role_id', sa.BigInteger(), nullable=True),
    sa.Column('role_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=120), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('modified_by', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role_masters.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_roles_id'), 'user_roles', ['id'], unique=False)
    op.create_table('cpmks',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('perkuliahan_id', sa.BigInteger(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('statement', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=120), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('modified_by', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['perkuliahan_id'], ['perkuliahans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cpmks_id'), 'cpmks', ['id'], unique=False)
    op.create_table('mapping_mahasiswas',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('perkuliahan_id', sa.BigInteger(), nullable=True),
    sa.Column('mahasiswa_id', sa.BigInteger(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=120), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('modified_by', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['mahasiswa_id'], ['mahasiswas.id'], ),
    sa.ForeignKeyConstraint(['perkuliahan_id'], ['perkuliahans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mapping_mahasiswas_id'), 'mapping_mahasiswas', ['id'], unique=False)
    op.create_table('persentase_pks',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('perkuliahan_id', sa.BigInteger(), nullable=True),
    sa.Column('nilai_tugas', sa.String(length=200), nullable=True),
    sa.Column('nilai_uts', sa.String(length=200), nullable=True),
    sa.Column('nilai_uas', sa.String(length=200), nullable=True),
    sa.Column('nilai_praktek', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=120), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('modified_by', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['perkuliahan_id'], ['perkuliahans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_persentase_pks_id'), 'persentase_pks', ['id'], unique=False)
    op.create_table('mapping_cpmk_cpls',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('cpmk_id', sa.BigInteger(), nullable=True),
    sa.Column('cpl_id', sa.BigInteger(), nullable=True),
    sa.Column('value', sa.String(length=150), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=120), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('modified_by', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['cpl_id'], ['cpls.id'], ),
    sa.ForeignKeyConstraint(['cpmk_id'], ['cpmks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mapping_cpmk_cpls_id'), 'mapping_cpmk_cpls', ['id'], unique=False)
    op.create_table('nilai_prakteks',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('mapping_mhs_id', sa.BigInteger(), nullable=True),
    sa.Column('cpmk_id', sa.BigInteger(), nullable=True),
    sa.Column('nilai_praktek', sa.DECIMAL(), nullable=True),
    sa.Column('nilai_cpmk', sa.DECIMAL(), nullable=True),
    sa.Column('bobot_cpmk', sa.DECIMAL(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=120), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('modified_by', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['cpmk_id'], ['cpmks.id'], ),
    sa.ForeignKeyConstraint(['mapping_mhs_id'], ['mapping_mahasiswas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nilai_prakteks_id'), 'nilai_prakteks', ['id'], unique=False)
    op.create_table('nilai_tugas',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('mapping_mhs_id', sa.BigInteger(), nullable=True),
    sa.Column('cpmk_id', sa.BigInteger(), nullable=True),
    sa.Column('nilai_tugas', sa.DECIMAL(), nullable=True),
    sa.Column('nilai_cpmk', sa.DECIMAL(), nullable=True),
    sa.Column('bobot_cpmk', sa.DECIMAL(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=120), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('modified_by', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['cpmk_id'], ['cpmks.id'], ),
    sa.ForeignKeyConstraint(['mapping_mhs_id'], ['mapping_mahasiswas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nilai_tugas_id'), 'nilai_tugas', ['id'], unique=False)
    op.create_table('nilai_uas',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('mapping_mhs_id', sa.BigInteger(), nullable=True),
    sa.Column('cpmk_id', sa.BigInteger(), nullable=True),
    sa.Column('nilai_uas', sa.DECIMAL(), nullable=True),
    sa.Column('nilai_cpmk', sa.DECIMAL(), nullable=True),
    sa.Column('bobot_cpmk', sa.DECIMAL(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=120), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('modified_by', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['cpmk_id'], ['cpmks.id'], ),
    sa.ForeignKeyConstraint(['mapping_mhs_id'], ['mapping_mahasiswas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nilai_uas_id'), 'nilai_uas', ['id'], unique=False)
    op.create_table('nilai_uts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('mapping_mhs_id', sa.BigInteger(), nullable=True),
    sa.Column('cpmk_id', sa.BigInteger(), nullable=True),
    sa.Column('nilai_uts', sa.DECIMAL(), nullable=True),
    sa.Column('nilai_cpmk', sa.DECIMAL(), nullable=True),
    sa.Column('bobot_cpmk', sa.DECIMAL(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=120), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('modified_by', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['cpmk_id'], ['cpmks.id'], ),
    sa.ForeignKeyConstraint(['mapping_mhs_id'], ['mapping_mahasiswas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nilai_uts_id'), 'nilai_uts', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_nilai_uts_id'), table_name='nilai_uts')
    op.drop_table('nilai_uts')
    op.drop_index(op.f('ix_nilai_uas_id'), table_name='nilai_uas')
    op.drop_table('nilai_uas')
    op.drop_index(op.f('ix_nilai_tugas_id'), table_name='nilai_tugas')
    op.drop_table('nilai_tugas')
    op.drop_index(op.f('ix_nilai_prakteks_id'), table_name='nilai_prakteks')
    op.drop_table('nilai_prakteks')
    op.drop_index(op.f('ix_mapping_cpmk_cpls_id'), table_name='mapping_cpmk_cpls')
    op.drop_table('mapping_cpmk_cpls')
    op.drop_index(op.f('ix_persentase_pks_id'), table_name='persentase_pks')
    op.drop_table('persentase_pks')
    op.drop_index(op.f('ix_mapping_mahasiswas_id'), table_name='mapping_mahasiswas')
    op.drop_table('mapping_mahasiswas')
    op.drop_index(op.f('ix_cpmks_id'), table_name='cpmks')
    op.drop_table('cpmks')
    op.drop_index(op.f('ix_user_roles_id'), table_name='user_roles')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_prodi_strukturals_id'), table_name='prodi_strukturals')
    op.drop_table('prodi_strukturals')
    op.drop_index(op.f('ix_perkuliahans_id'), table_name='perkuliahans')
    op.drop_table('perkuliahans')
    op.drop_index(op.f('ix_mhs_konsentrasis_id'), table_name='mhs_konsentrasis')
    op.drop_table('mhs_konsentrasis')
    op.drop_index(op.f('ix_matkul_konsentrasis_id'), table_name='matkul_konsentrasis')
    op.drop_table('matkul_konsentrasis')
    op.drop_index(op.f('ix_mahasiswa_doswals_id'), table_name='mahasiswa_doswals')
    op.drop_table('mahasiswa_doswals')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_role_permissions_id'), table_name='role_permissions')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_mata_kuliahs_id'), table_name='mata_kuliahs')
    op.drop_table('mata_kuliahs')
    op.drop_index(op.f('ix_mahasiswas_id'), table_name='mahasiswas')
    op.drop_table('mahasiswas')
    op.drop_index(op.f('ix_konsentrasi_prodis_id'), table_name='konsentrasi_prodis')
    op.drop_table('konsentrasi_prodis')
    op.drop_index(op.f('ix_cpls_id'), table_name='cpls')
    op.drop_table('cpls')
    op.drop_index(op.f('ix_child_modules_id'), table_name='child_modules')
    op.drop_table('child_modules')
    op.drop_index(op.f('ix_prodis_id'), table_name='prodis')
    op.drop_table('prodis')
    op.drop_index(op.f('ix_modules_id'), table_name='modules')
    op.drop_table('modules')
    op.drop_index(op.f('ix_status_mahasiswas_id'), table_name='status_mahasiswas')
    op.drop_table('status_mahasiswas')
    op.drop_index(op.f('ix_role_masters_id'), table_name='role_masters')
    op.drop_table('role_masters')
    op.drop_index(op.f('ix_module_groups_id'), table_name='module_groups')
    op.drop_table('module_groups')
    op.drop_index(op.f('ix_kurikulums_id'), table_name='kurikulums')
    op.drop_table('kurikulums')
    op.drop_index(op.f('ix_konsentrasis_id'), table_name='konsentrasis')
    op.drop_table('konsentrasis')
    op.drop_index(op.f('ix_fakultas_id'), table_name='fakultas')
    op.drop_table('fakultas')
    # ### end Alembic commands ###
