"""First migrate

Revision ID: 8a650f8853e2
Revises: 66a17135ad01
Create Date: 2023-07-06 01:44:50.861917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a650f8853e2'
down_revision = '66a17135ad01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('assessment_matkul_details_tahun_ajaran_id_fkey', 'assessment_matkul_details', type_='foreignkey')
    op.drop_constraint('assessment_matkul_details_cpl_id_fkey', 'assessment_matkul_details', type_='foreignkey')
    op.drop_column('assessment_matkul_details', 'tahun_ajaran_id')
    op.drop_column('assessment_matkul_details', 'cpl_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assessment_matkul_details', sa.Column('cpl_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('assessment_matkul_details', sa.Column('tahun_ajaran_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.create_foreign_key('assessment_matkul_details_cpl_id_fkey', 'assessment_matkul_details', 'cpls', ['cpl_id'], ['id'])
    op.create_foreign_key('assessment_matkul_details_tahun_ajaran_id_fkey', 'assessment_matkul_details', 'tahun_ajarans', ['tahun_ajaran_id'], ['id'])
    # ### end Alembic commands ###
