"""create perkuliahan

Revision ID: 939b05b91ce8
Revises: 226fa76592fe
Create Date: 2023-07-27 10:52:17.212267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '939b05b91ce8'
down_revision = '226fa76592fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
